@work_item_tracker_api_HostAddress = http://localhost:5000


POST {{work_item_tracker_api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "Username": "testuser",
  "Password": "testpassword"
}

###

GET {{work_item_tracker_api_HostAddress}}/api/workitems/
Accept: application/json
Authorization: Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImVtYWlsIjoidGVzdHVzZXIiLCJleHAiOjE3NzM3NTgzOTd9.nqYiSAzk97JxkHF_oaXH3HqbzWh9M6MffX-KO4acnfc

###

POST {{work_item_tracker_api_HostAddress}}/api/workitems/
Content-Type: application/json

{
  "title": "Navbar issue",
  "description": "The navbar should be fixed."
}

###

GET {{work_item_tracker_api_HostAddress}}/api/workitems/6
Accept: application/json

###

PUT {{work_item_tracker_api_HostAddress}}/api/workitems/5
Content-Type: application/json  

{
  "id": 5,
  "title": "Fix login issue",
  "description": "Updated description for the task.",
  "status": "closed"
}

###

GET {{work_item_tracker_api_HostAddress}}/api/workitems/
Accept: application/json


###

POST {{work_item_tracker_api_HostAddress}}/api/workitems/
Content-Type: application/json

{
  "title": "New Task 2",
  "description": "This is a new task created via API."
}

###

GET {{work_item_tracker_api_HostAddress}}/api/workitems/search?query=Task
Accept: application/json

###

DELETE {{work_item_tracker_api_HostAddress}}/api/workitems/1

###

GET {{work_item_tracker_api_HostAddress}}/api/workitems/status/open
Accept: application/json

###
GET {{work_item_tracker_api_HostAddress}}/api/workitems/timeframe/60
Accept: application/json